using System.Drawing;
using System.Windows.Forms;

namespace OmniVCamController
{
    public sealed partial class MainForm
    {
        private TextBox hostBox;
        private NumericUpDown portBox;
        private TextBox inputBox;
        private TextBox titleBox;
        private TextBox optionsBox;
        private ComboBox hwDecodeBox;
        private ComboBox scaleModeBox;
        private ComboBox displayAspectBox;
        private TextBox videoFilterBox;
        private TextBox audioFilterBox;
        private CheckBox autoDeinterlaceBox;
        private ComboBox autoDeinterlaceFilterBox;
        private NumericUpDown videoIndexBox;
        private NumericUpDown audioIndexBox;
        private NumericUpDown shiftBox;
        private NumericUpDown seekBox;
        private Label positionLabel;
        private Label deliverLabel;
        private TrackBar progressBar;
        private CheckBox byteSeekBox;
        private TextBox logBox;
        private ListView favoriteInputView;
        private ListView scheduledPlaylistView;
        private ListView playlistView;
        private Label playoutStatusLabel;
        private ComboBox playoutModeBox;
        private ComboBox scheduleTypeBox;
        private DateTimePicker scheduleDateTimePicker;
        private DateTimePicker scheduleTimePicker;
        private CheckBox mondayBox;
        private CheckBox tuesdayBox;
        private CheckBox wednesdayBox;
        private CheckBox thursdayBox;
        private CheckBox fridayBox;
        private CheckBox saturdayBox;
        private CheckBox sundayBox;
        private CheckBox scheduleEndBox;
        private DateTimePicker scheduleEndPicker;
        private TextBox scheduledTitleBox;
        private TextBox scheduledOptionsBox;
        private CheckBox writeNowPlayingXmlBox;
        private ComboBox scheduleEndActionBox;
        private ComboBox scheduleStartActionBox;
        private CheckBox autoAdvanceBox;
        private CheckBox scheduledStartBox;
        private DateTimePicker scheduledStartPicker;
        private Panel mainContentPanel;
        private TabControl connectionTabs;
        private Button addTabButton;
        private Button removeTabButton;

        private void InitializeComponent()
        {
            hostBox = new TextBox();
            portBox = new NumericUpDown();
            inputBox = new TextBox();
            titleBox = new TextBox();
            optionsBox = new TextBox();
            hwDecodeBox = new ComboBox();
            scaleModeBox = new ComboBox();
            displayAspectBox = new ComboBox();
            videoFilterBox = new TextBox();
            audioFilterBox = new TextBox();
            autoDeinterlaceBox = new CheckBox();
            autoDeinterlaceFilterBox = new ComboBox();
            videoIndexBox = new NumericUpDown();
            audioIndexBox = new NumericUpDown();
            shiftBox = new NumericUpDown();
            seekBox = new NumericUpDown();
            positionLabel = new Label();
            deliverLabel = new Label();
            progressBar = new TrackBar();
            byteSeekBox = new CheckBox();
            logBox = new TextBox();
            favoriteInputView = new ListView();

            scheduledPlaylistView = new ListView();
            playlistView = new ListView();
            playoutStatusLabel = new Label();
            playoutModeBox = new ComboBox();
            scheduleTypeBox = new ComboBox();
            scheduleDateTimePicker = new DateTimePicker();
            scheduleTimePicker = new DateTimePicker();
            mondayBox = new CheckBox();
            tuesdayBox = new CheckBox();
            wednesdayBox = new CheckBox();
            thursdayBox = new CheckBox();
            fridayBox = new CheckBox();
            saturdayBox = new CheckBox();
            sundayBox = new CheckBox();
            scheduleEndBox = new CheckBox();
            scheduleEndPicker = new DateTimePicker();
            scheduledTitleBox = new TextBox();
            scheduledOptionsBox = new TextBox();
            writeNowPlayingXmlBox = new CheckBox();
            scheduleEndActionBox = new ComboBox();
            scheduleStartActionBox = new ComboBox();
            autoAdvanceBox = new CheckBox();
            scheduledStartBox = new CheckBox();
            scheduledStartPicker = new DateTimePicker();
            statusTimer = new Timer();
            playoutTimer = new Timer();

            mainContentPanel = new Panel();
            connectionTabs = new TabControl();
            addTabButton = new Button();
            removeTabButton = new Button();

            ((System.ComponentModel.ISupportInitialize)(portBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(videoIndexBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(audioIndexBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(shiftBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(seekBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(progressBar)).BeginInit();
            SuspendLayout();

            Text = "OmniVCam Controller";
            MinimumSize = new Size(820, 600);
            Size = new Size(980, 680);
            Font = new Font("Segoe UI", 9F);

            hostBox.Text = "127.0.0.1";
            portBox.Minimum = 1;
            portBox.Maximum = 65535;
            portBox.Value = 16999;
            inputBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            titleBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            optionsBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            hwDecodeBox.DropDownStyle = ComboBoxStyle.DropDown;
            scaleModeBox.DropDownStyle = ComboBoxStyle.DropDownList;
            displayAspectBox.DropDownStyle = ComboBoxStyle.DropDown;
            videoFilterBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            audioFilterBox.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            autoDeinterlaceBox.Text = string.Empty;
            autoDeinterlaceBox.Checked = true;
            autoDeinterlaceBox.AutoSize = true;
            autoDeinterlaceBox.Anchor = AnchorStyles.Left;
            autoDeinterlaceFilterBox.DropDownStyle = ComboBoxStyle.DropDownList;
            videoIndexBox.Minimum = -1;
            videoIndexBox.Maximum = 128;
            videoIndexBox.Value = -1;
            audioIndexBox.Minimum = -1;
            audioIndexBox.Maximum = 128;
            audioIndexBox.Value = -1;
            shiftBox.Minimum = 0;
            shiftBox.Maximum = 41700;
            shiftBox.Increment = 1500;
            shiftBox.Width = 90;
            seekBox.Maximum = 86400;
            seekBox.Width = 90;
            positionLabel.Text = "00:00:00 / --:--:--";
            positionLabel.AutoSize = true;
            positionLabel.Anchor = AnchorStyles.Left;
            positionLabel.Padding = new Padding(0, 4, 0, 0);
            deliverLabel.Text = Resources.AppStrings.ResourceManager.GetString("FrameDeliverBlockTimeEmpty") ?? "Frame deliver block time: -- / -- ms";
            deliverLabel.AutoSize = true;
            deliverLabel.Anchor = AnchorStyles.Left;
            deliverLabel.Padding = new Padding(12, 4, 0, 0);
            progressBar.Minimum = 0;
            progressBar.Maximum = 10000;
            progressBar.TickFrequency = 1000;
            progressBar.SmallChange = 10;
            progressBar.LargeChange = 500;
            progressBar.Dock = DockStyle.Fill;
            byteSeekBox.Text = Resources.AppStrings.ResourceManager.GetString("ByteSeek") ?? "Byte seek";
            byteSeekBox.AutoSize = true;
            byteSeekBox.Anchor = AnchorStyles.Left;
            byteSeekBox.Padding = new Padding(0, 4, 0, 0);
            logBox.Multiline = true;
            logBox.ReadOnly = true;
            logBox.ScrollBars = ScrollBars.Vertical;
            logBox.Dock = DockStyle.Fill;
            favoriteInputView.Dock = DockStyle.Fill;
            favoriteInputView.View = View.Details;
            favoriteInputView.FullRowSelect = true;
            favoriteInputView.GridLines = true;
            favoriteInputView.HideSelection = false;
            scheduledPlaylistView.Dock = DockStyle.Fill;
            scheduledPlaylistView.View = View.Details;
            scheduledPlaylistView.FullRowSelect = true;
            scheduledPlaylistView.GridLines = true;
            scheduledPlaylistView.HideSelection = false;
            playlistView.Dock = DockStyle.Fill;
            playlistView.View = View.Details;
            playlistView.FullRowSelect = true;
            playlistView.GridLines = true;
            playlistView.HideSelection = false;
            playoutStatusLabel.Text = Resources.AppStrings.ResourceManager.GetString("PlayoutStatusStopped") ?? "Playout: stopped";
            playoutStatusLabel.AutoSize = true;
            playoutStatusLabel.Padding = new Padding(6, 5, 0, 0);
            playoutModeBox.DropDownStyle = ComboBoxStyle.DropDownList;
            scheduleTypeBox.DropDownStyle = ComboBoxStyle.DropDownList;
            scheduleDateTimePicker.Format = DateTimePickerFormat.Custom;
            scheduleDateTimePicker.CustomFormat = "yyyy-MM-dd HH:mm:ss";
            scheduleDateTimePicker.Width = 150;
            scheduleTimePicker.Format = DateTimePickerFormat.Time;
            scheduleTimePicker.ShowUpDown = true;
            scheduleTimePicker.Width = 90;
            mondayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekMonday") ?? "Mon";
            tuesdayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekTuesday") ?? "Tue";
            wednesdayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekWednesday") ?? "Wed";
            thursdayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekThursday") ?? "Thu";
            fridayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekFriday") ?? "Fri";
            saturdayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekSaturday") ?? "Sat";
            sundayBox.Text = Resources.AppStrings.ResourceManager.GetString("WeekSunday") ?? "Sun";
            mondayBox.AutoSize = true;
            tuesdayBox.AutoSize = true;
            wednesdayBox.AutoSize = true;
            thursdayBox.AutoSize = true;
            fridayBox.AutoSize = true;
            saturdayBox.AutoSize = true;
            sundayBox.AutoSize = true;
            scheduleEndBox.Text = Resources.AppStrings.ResourceManager.GetString("UseEndTime") ?? "Use end time";
            scheduleEndBox.AutoSize = true;
            scheduleEndPicker.Format = DateTimePickerFormat.Custom;
            scheduleEndPicker.CustomFormat = "yyyy-MM-dd HH:mm:ss";
            scheduleEndPicker.Width = 150;
            scheduledTitleBox.Width = 220;
            scheduledOptionsBox.Width = 260;
            writeNowPlayingXmlBox.Text = Resources.AppStrings.ResourceManager.GetString("WriteNowPlayingXml") ?? "Write now playing XML";
            writeNowPlayingXmlBox.Checked = true;
            writeNowPlayingXmlBox.AutoSize = true;
            scheduleEndActionBox.DropDownStyle = ComboBoxStyle.DropDownList;
            scheduleStartActionBox.DropDownStyle = ComboBoxStyle.DropDownList;
            autoAdvanceBox.Text = Resources.AppStrings.ResourceManager.GetString("NormalAutoNext") ?? "Normal auto next";
            autoAdvanceBox.Checked = true;
            autoAdvanceBox.AutoSize = true;
            scheduledStartBox.Text = Resources.AppStrings.ResourceManager.GetString("StartAt") ?? "Start at";
            scheduledStartBox.AutoSize = true;
            scheduledStartPicker.Format = DateTimePickerFormat.Time;
            scheduledStartPicker.ShowUpDown = true;
            scheduledStartPicker.Width = 90;
            statusTimer.Interval = 1000;
            playoutTimer.Interval = 1000;

            mainContentPanel.Dock = DockStyle.Fill;
            mainContentPanel.Name = "mainContentPanel";
            connectionTabs.Dock = DockStyle.Top;
            connectionTabs.Height = 30;
            connectionTabs.Name = "connectionTabs";
            addTabButton.Text = "+";
            addTabButton.Width = 28;
            addTabButton.Height = 24;
            removeTabButton.Text = "-";
            removeTabButton.Width = 28;
            removeTabButton.Height = 24;
            Controls.Add(mainContentPanel);
            Controls.Add(connectionTabs);

            ((System.ComponentModel.ISupportInitialize)(portBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(videoIndexBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(audioIndexBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(shiftBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(seekBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(progressBar)).EndInit();
            ResumeLayout(false);
        }
    }
}
