//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniVCamController.Resources
{
    using System.Globalization;
    using System.Resources;

    internal class AppStrings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal AppStrings()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager("OmniVCamController.Resources.AppStrings", typeof(AppStrings).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
    }
}
